/*
 * Copyright (c) 2006 - 2010 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.common.bobrowser.crud.gui.component;

import de.linogistix.common.bobrowser.crud.gui.object.BOCreateNode;
import de.linogistix.common.bobrowser.api.BOLookup;
import de.linogistix.common.bobrowser.bo.editor.BOEditorHeader;
import de.linogistix.common.bobrowser.bo.BO;
import de.linogistix.common.res.CommonBundleResolver;
import java.beans.BeanInfo;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import org.openide.explorer.propertysheet.PropertySheet;
import org.openide.nodes.Node;
import org.openide.util.Lookup;
import org.openide.util.NbBundle;

/**
 *
 * @author  trautm
 */
public class BOCreateJPanel1 extends javax.swing.JPanel {
  
  private Logger log = Logger.getLogger(BOCreateJPanel1.class.getName());
  
  BOCreateNode node;
  
  /**
   * Creates new form BOCreateJPanel1
   */
  public BOCreateJPanel1(BOCreateNode node) {
    
    this.node= node;
    
    initComponents();
    initPropertySheet();
    initHeader();
    setName(NbBundle.getMessage(CommonBundleResolver.class,"BOCreateWizard.Title"));

  }

  private void initHeader() {
    BOLookup l = (BOLookup)Lookup.getDefault().lookup(BOLookup.class);
    BO bo = (BO)l.lookup(node.getBo().getClass());
    
    String title = NbBundle.getMessage(CommonBundleResolver.class, "boCreate", new String[]{bo.getSingularDisplayName()});
   
    BOEditorHeader h = new BOEditorHeader(
            new ImageIcon(node.getIcon(BeanInfo.	ICON_COLOR_32x32 )), 
             title ,"");
    headerPanel.add(h);
  }
  
  private void initPropertySheet(){
    SwingUtilities.invokeLater(new Runnable() {
      public void run() {
        PropertySheet ps;
        ps = new PropertySheet();
        ps.setNodes(new Node[]{node});
        editorPanel.add(ps);     
      }
    });
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    headerPanel = new javax.swing.JPanel();
    editorPanel = new javax.swing.JPanel();

    setLayout(new java.awt.BorderLayout());

    headerPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
    add(headerPanel, java.awt.BorderLayout.NORTH);

    editorPanel.setLayout(new java.awt.BorderLayout());
    add(editorPanel, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel editorPanel;
  private javax.swing.JPanel headerPanel;
  // End of variables declaration//GEN-END:variables

  boolean implIsValid() {
    return true;
  }

  void implReadSettings(Object settings) {
   
   
  }

  void implStoreSettings(Object settings) {
   BOCreateWizard w = (BOCreateWizard)settings;
  }
}
