package de.linogistix.mobile.processes.replenish;

public enum ReplenishNavigation {

	REPLENISH_MENU,
	REPLENISH_MAIN_MENU,
	REPLENISH_START_PROCESS,
	REPLENISH_START_REQUEST,
	
	REPLENISH_ORDER_SELECT,
	REPLENISH_ORDER_DONE,
	REPLENISH_ORDER_CANCEL,
	REPLENISH_SOURCE_LOCATION,
	REPLENISH_SOURCE_CONFIRM,
	REPLENISH_SOURCE_AMOUNT,
	REPLENISH_DESTINATION_LOCATION,
	REPLENISH_DESTINATION_CONFIRM,
	
	REPLENISH_REQ_LOCATION,
	REPLENISH_REQ_AMOUNT,
	REPLENISH_REQ_INFO,

}
