/*
 * Copyright (c) 2006 - 2010 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.inventory.report.querystockunits.gui.gui_builder;

import de.linogistix.common.gui.component.controls.BOAutoFilteringComboBox;
import de.linogistix.common.gui.listener.TopComponentListener;
import de.linogistix.inventory.report.querystockunits.gui.component.CenterPanel;
import de.linogistix.inventory.report.querystockunits.gui.component.HeaderPanel;
import java.awt.BorderLayout;
import javax.swing.BorderFactory;
import org.mywms.model.ItemData;
import org.openide.windows.TopComponent;

/**
 *
 * @author  trautm
 */
public class TopComponentPanel extends javax.swing.JPanel implements TopComponentListener{

    HeaderPanel headerPanel ;
    CenterPanel centerPanel ;
    
    /** Creates new form TopComponentPanel */
    public TopComponentPanel(TopComponent topComponent) {
    }
    
    public void initTopComponent(){
        invalidate();
        initComponents();
        postInit();
        validate();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    private void postInit() {
        setBorder(BorderFactory.createEmptyBorder(0,10,0,10));
        headerPanel = new HeaderPanel(this);
        centerPanel = new CenterPanel(this);    
        
        add(headerPanel, BorderLayout.NORTH);
        add(centerPanel, BorderLayout.CENTER);
        
    }

    public void componentOpened() {
     initTopComponent();
    }

    public void componentClosed() {
    }

    public void componentActivated() {
    }

    public void componentDeactivated() {
    }

    public void componentHidden() {
    }

    public void componentShowing() {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
