/*
 * Copyright (c) 2006 - 2010 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.los.inventory.ws.manage_itemdata;

public enum ManageItemDataErrorCodes {
	ERROR_UNKNOWN_CLIENT, 
	ERROR_UNKNOWN_ITEMUNIT, 
	UPDATE_ERROR_ITEMUNIT_STOCK_EXIST, 
	UPDATE_ERROR_SCALE_STOCK_EXIST, 
	UPDATE_ERROR_LOTMANDATORY_STOCK_EXIST, 
	UPDATE_ERROR_SERIALRECORDTYPE_STOCK_EXIST, 
	DELETE_ERROR_UNKNOWN_ITEMNUMBER, 
	DELETE_ERROR_STOCK_EXIST, 
	UNAUTHORIZED_CALLER, 
	ERROR_ITEMNAME_NULL,
	ERROR_UNKNOWN_ITEMDATA,
	ERROR_UPDATE_BOM,
	ERROR_DELETE

}
