/*
 * Copyright (c) 2006 - 2010 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.inventory.report.queryinventory;

import de.linogistix.common.gui.component.other.TopComponentExt;
import de.linogistix.common.services.J2EEServiceLocator;
import de.linogistix.reports.res.ReportsBundleResolver;
import de.linogistix.inventory.report.queryinventory.gui.component.TopComponentPanel;
import de.linogistix.los.model.LOSCommonPropertyKey;
import java.io.Serializable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import org.openide.explorer.ExplorerUtils;
import org.openide.util.Lookup;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
//import org.openide.util.Utilities;

/**
 * Top component which displays something.
 */
final class QueryInventoryTopComponent extends TopComponentExt {

    private final static Logger log = Logger.getLogger(QueryInventoryTopComponent.class.getName());
    
    private static QueryInventoryTopComponent instance;
    /** path to the icon used by the component and its open action */
//    static final String ICON_PATH = "SET/PATH/TO/ICON/HERE";

    private static final String PREFERRED_ID = "QueryInventoryTopComponent";
    private TopComponentPanel topComponentPanel = new TopComponentPanel(this);

    private QueryInventoryTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(ReportsBundleResolver.class, "CTL_QueryInventoryTopComponent"));
        setToolTipText(NbBundle.getMessage(ReportsBundleResolver.class, "HINT_QueryInventoryTopComponent"));
        postInit();
        initLookup();
//        setIcon(Utilities.loadImage(ICON_PATH, true));
    }
    
     protected void initLookup() {
        ActionMap map = getActionMap();
        InputMap keys = getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);

        try {        
            associateLookup(ExplorerUtils.createLookup(
                    topComponentPanel.centerPanel.treeTablePanel.getExplorerManager(), map));
        } catch (IllegalStateException ex) {
            //already done!?
            log.log(Level.INFO, ex.getMessage(), ex);
            return;
        }
    }

    @Override
    public int getPersistenceType() {
        J2EEServiceLocator loc = (J2EEServiceLocator) Lookup.getDefault().lookup(J2EEServiceLocator.class);
        if( loc.getPropertyBool(LOSCommonPropertyKey.NBCLIENT_RESTORE_TABS, true) ) {
            return TopComponent.PERSISTENCE_ONLY_OPENED;
        }
        else {
            return TopComponent.PERSISTENCE_NEVER;
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link findInstance}.
     */
    public static synchronized QueryInventoryTopComponent getDefault() {
        if (instance == null) {
            instance = new QueryInventoryTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the QueryInventoryTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized QueryInventoryTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(QueryInventoryTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof QueryInventoryTopComponent) {
            return (QueryInventoryTopComponent) win;
        }
        Logger.getLogger(QueryInventoryTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID +
                "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }


    /** replaces this in object stream */
    @Override
    public Object writeReplace() {
        return new ResolvableHelper();
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }

    final static class ResolvableHelper implements Serializable {

        private static final long serialVersionUID = 1L;

        public Object readResolve() {
            return QueryInventoryTopComponent.getDefault();
        }
    }
    
    private void postInit() {
        add(topComponentPanel);
    }
    
}
