/*
 * Copyright (c) 2006 - 2010 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.wmsprocesses.processes.treat_order.gui.component;

import java.awt.BorderLayout;
import javax.swing.BorderFactory;
import org.openide.windows.TopComponent;

/**
 *
 * @author  Jordan
 */
public class TreatOrderTopComponentPanel extends javax.swing.JPanel {

    private TreatOrderHeaderPanel headerPanel = new TreatOrderHeaderPanel(this);
    
    private TreatOrderCenterPanel centerPanel = new TreatOrderCenterPanel();
    
    private TreatOrderFooterPanel footerPanel = new TreatOrderFooterPanel(this);
    
    TopComponent topComponent;
    
    /** Creates new form TreatOrderTopComponentPanel */
    public TreatOrderTopComponentPanel( TopComponent topComponent ) {
        initComponents();
        
        setBorder(BorderFactory.createEmptyBorder(0,10,0,10));
        
        add(headerPanel, BorderLayout.NORTH);
        add(centerPanel, BorderLayout.CENTER);
        add(footerPanel, BorderLayout.SOUTH);
        
        this.topComponent = topComponent;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public TreatOrderCenterPanel getCenterPanel(){
        return centerPanel;
    }
}
