package de.linogistix.mobile.processes.info;

public enum InfoNavigation {

	INFO_BACK_TO_MENU,
	INFO_ENTER_CODE,
	INFO_SELECT_TYPE,
	INFO_SHOW_UNITLOAD,
	INFO_SHOW_UNITLOAD_STOCK,
	INFO_SHOW_ITEMDATA,
	INFO_SHOW_ITEMDATA_DESCR,
	INFO_SHOW_LOCATION,
	INFO_SHOW_STOCKUNIT,
	INFO_SHOW_ORDER
	
}
