package de.linogistix.mobile.processes.picking;

public enum PickingMobileNavigation {

	PICK_MENU,
	PICK_START,
	PICK_ORDER_SELECT,
	PICK_ORDER_INFO,
	PICK_ORDER_SUMMARY,
	PICK_ORDER_DONE,
	PICK_PICKFROM,
	PICK_PICKFROM_FUNCTION,
	PICK_PICK,
	PICK_PICK_FUNCTION,
	PICK_PICK_SERIAL,
	PICK_PICK_REMAINING,
	PICK_PICK_MISSING,
	PICK_PICK_EMPTY,
	PICK_PICK_DONE,
	PICK_PICKTO_COMPLETED,
	PICK_PICKTO_LABEL_POSTPICK,
	PICK_PICKTO_TARGET,
	PICK_PICKTO_PRINT
	
}
