/*
 * Copyright (c) 2006 - 2012 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.wmsprocesses.processes.goodsreceipt.gui.gui_builder;

import de.linogistix.common.gui.component.controls.LOSNumericFormattedTextField;

/**
 *
 * @author  trautm
 */
public abstract class AbstractPositionWizardSUPanelUI extends javax.swing.JPanel {

    /** Creates new form AbstractPositionWizardULPanel */
    public AbstractPositionWizardSUPanelUI() {
        initComponents();
    }

    public LOSNumericFormattedTextField getUnitLoadAmountTextField(){
        return (LOSNumericFormattedTextField) unitLoadAmountTextField;
    }

    //------------------------------------------------------------------------
    
  

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        itemDataComboBoxPanel = new javax.swing.JPanel();
        adviceComboBoxPanel = new javax.swing.JPanel();
        amountTextField = new de.linogistix.common.gui.component.controls.LOSNumericFormattedTextField();
        unitLoadAmountTextField = new LOSNumericFormattedTextField();

        setLayout(new java.awt.GridBagLayout());

        itemDataComboBoxPanel.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        add(itemDataComboBoxPanel, gridBagConstraints);

        adviceComboBoxPanel.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        add(adviceComboBoxPanel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        add(amountTextField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(unitLoadAmountTextField, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JPanel adviceComboBoxPanel;
    protected javax.swing.JPanel amountTextField;
    protected javax.swing.JPanel itemDataComboBoxPanel;
    private javax.swing.JPanel unitLoadAmountTextField;
    // End of variables declaration//GEN-END:variables
}
