/*
 * Copyright (c) 2006 - 2012 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.wmsprocesses.processes.goodsreceipt.gui.gui_builder;

import de.linogistix.common.gui.component.controls.LOSComboBox;
import de.linogistix.common.gui.component.controls.LOSDateFormattedTextField;
import de.linogistix.wmsprocesses.res.WMSProcessesBundleResolver;

/**
 *
 * @author  trautm
 */
public class AbstractCreateWizardDetailPanel extends javax.swing.JPanel {

    /** Creates new form AbstractCreateWizardDetailPanel */
    public AbstractCreateWizardDetailPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        goodsReceiptPanel = new javax.swing.JPanel();
        orderTypeField = new LOSComboBox();
        clientComboBoxPanel = new javax.swing.JPanel();
        delivererTextfield = new javax.swing.JTextField();
        delivererLabel = new javax.swing.JLabel();
        externNumberLabel = new javax.swing.JLabel();
        externNumberTextfield = new javax.swing.JTextField();
        datePanel = new LOSDateFormattedTextField();
        gateComboBox = new de.linogistix.common.gui.component.controls.LOSComboBox();
        senderField = new javax.swing.JTextField();
        senderLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        goodsReceiptPanel.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        goodsReceiptPanel.add(orderTypeField, gridBagConstraints);

        clientComboBoxPanel.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        goodsReceiptPanel.add(clientComboBoxPanel, gridBagConstraints);

        delivererTextfield.setColumns(12);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        goodsReceiptPanel.add(delivererTextfield, gridBagConstraints);

        delivererLabel.setText(org.openide.util.NbBundle.getMessage(WMSProcessesBundleResolver.class, "GoodsreceiptCenterPanel.deliverer")); // NOI18N
        delivererLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        delivererLabel.setMaximumSize(new java.awt.Dimension(150, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        goodsReceiptPanel.add(delivererLabel, gridBagConstraints);

        externNumberLabel.setText(org.openide.util.NbBundle.getMessage(WMSProcessesBundleResolver.class, "AbstractCenterPanel.externNumberLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        goodsReceiptPanel.add(externNumberLabel, gridBagConstraints);

        externNumberTextfield.setColumns(12);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        goodsReceiptPanel.add(externNumberTextfield, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        goodsReceiptPanel.add(datePanel, gridBagConstraints);

        gateComboBox.setTitle("Gate");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        goodsReceiptPanel.add(gateComboBox, gridBagConstraints);

        senderField.setColumns(12);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        goodsReceiptPanel.add(senderField, gridBagConstraints);

        senderLabel.setText("Sender");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        goodsReceiptPanel.add(senderLabel, gridBagConstraints);

        add(goodsReceiptPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JPanel clientComboBoxPanel;
    protected javax.swing.JPanel datePanel;
    private javax.swing.JLabel delivererLabel;
    protected javax.swing.JTextField delivererTextfield;
    private javax.swing.JLabel externNumberLabel;
    protected javax.swing.JTextField externNumberTextfield;
    protected de.linogistix.common.gui.component.controls.LOSComboBox gateComboBox;
    private javax.swing.JPanel goodsReceiptPanel;
    private javax.swing.JPanel orderTypeField;
    protected javax.swing.JTextField senderField;
    private javax.swing.JLabel senderLabel;
    // End of variables declaration//GEN-END:variables

    public LOSComboBox getOrderTypeField(){
        return (LOSComboBox) orderTypeField;
    }
}
