/*
 * Copyright (c) 2006 - 2012 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.wmsprocesses.processes.goodsreceipt.gui.gui_builder;

import de.linogistix.common.gui.component.controls.BOAutoFilteringComboBox;
import de.linogistix.common.gui.component.controls.LOSComboBox;
import de.linogistix.common.gui.component.controls.LOSTextField;
import de.linogistix.wmsprocesses.res.WMSProcessesBundleResolver;
import de.wms2.mywms.inventory.UnitLoadType;
import java.awt.BorderLayout;
import java.awt.event.ItemEvent;
import org.openide.util.NbBundle;

/**
 *
 * @author  trautm
 */
public abstract class AbstractPositionWizardULPanelUI extends javax.swing.JPanel {

    protected BOAutoFilteringComboBox<UnitLoadType> unitLoadTypeComboBox = null;
    
    protected LOSTextField unitLoadLabelTextField;
    
    protected abstract void identifyULButtonItemStateChangedListener(ItemEvent evt);
     
    protected abstract void systemULButtonItemStateChangedListener(ItemEvent evt) ;
    
    public abstract void clear() ;
    
    /** Creates new form AbstractPositionWizardULPanel */
    public AbstractPositionWizardULPanelUI() {
        initComponents();
        postInit();
    }

    protected void postInit(){
        unitLoadLabelTextFieldPanel.add(getUnitLoadLabelTextField(), BorderLayout.CENTER);
        unitLoadTypeComboBoxPanel.add(getUnitLoadTypeComboBox(), BorderLayout.WEST);       
        
        getGoodsReceiptTypeComboBox().setTitle(
                NbBundle.getMessage(WMSProcessesBundleResolver.class, "GoodsreceiptCenterPanel.receiptType"));
    }

    //------------------------------------------------------------------------
    protected BOAutoFilteringComboBox<UnitLoadType> getUnitLoadTypeComboBox() {

        if (unitLoadTypeComboBox == null) {
            unitLoadTypeComboBox = new BOAutoFilteringComboBox<UnitLoadType>(UnitLoadType.class);
            unitLoadTypeComboBox.setSuppressWarnings(true);
            unitLoadTypeComboBox.getEditorLabel().setTitleText(NbBundle.getMessage(de.linogistix.location.res.LocationBundleResolver.class, "unitLoadType"));
        }

        return unitLoadTypeComboBox;
    }

    protected LOSTextField getUnitLoadLabelTextField() {
        if (unitLoadLabelTextField == null){
            unitLoadLabelTextField = new LOSTextField();
            unitLoadLabelTextField.setEnabled(true);
            unitLoadLabelTextField.setMandatory(true);
            unitLoadLabelTextField.setSuppressWarnings(true);
            unitLoadLabelTextField.setColumns(18);
            unitLoadLabelTextField.getTextFieldLabel().setTitleText(NbBundle.getMessage(WMSProcessesBundleResolver.class, "AbstractPositionWizardULPanelUI.unitLoadId"));
            unitLoadLabelTextFieldPanel.add(unitLoadLabelTextField, BorderLayout.CENTER);
        }
        return unitLoadLabelTextField;
    }

    public LOSComboBox getGoodsReceiptTypeComboBox(){
        return (LOSComboBox) goodsReceiptTypeComboBox;
    }
   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        identifyULButtonGroup = new javax.swing.ButtonGroup();
        goodsReceiptTypeComboBox = new LOSComboBox();
        unitLoadPanel = new javax.swing.JPanel();
        infoLabel = new javax.swing.JLabel();
        unitLoadLabelTextFieldPanel = new javax.swing.JPanel();
        unitLoadTypeComboBoxPanel = new javax.swing.JPanel();
        systemULButton = new javax.swing.JRadioButton();
        identifyULButton = new javax.swing.JRadioButton();

        setPreferredSize(new java.awt.Dimension(520, 126));
        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        add(goodsReceiptTypeComboBox, gridBagConstraints);

        unitLoadPanel.setLayout(new java.awt.GridBagLayout());

        infoLabel.setText(org.openide.util.NbBundle.getMessage(WMSProcessesBundleResolver.class, "AbstractPositionWizardULPanel.infoLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        unitLoadPanel.add(infoLabel, gridBagConstraints);

        unitLoadLabelTextFieldPanel.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 0, 0);
        unitLoadPanel.add(unitLoadLabelTextFieldPanel, gridBagConstraints);

        unitLoadTypeComboBoxPanel.setPreferredSize(new java.awt.Dimension(250, 50));
        unitLoadTypeComboBoxPanel.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        unitLoadPanel.add(unitLoadTypeComboBoxPanel, gridBagConstraints);

        identifyULButtonGroup.add(systemULButton);
        systemULButton.setText(org.openide.util.NbBundle.getMessage(WMSProcessesBundleResolver.class, "AbstractPositionWizardULPanelUI.systemULButton.text")); // NOI18N
        systemULButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                systemULButtonItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        unitLoadPanel.add(systemULButton, gridBagConstraints);

        identifyULButtonGroup.add(identifyULButton);
        identifyULButton.setText(org.openide.util.NbBundle.getMessage(WMSProcessesBundleResolver.class, "AbstractPositionWizardULPanelUI.identifyULButton.text")); // NOI18N
        identifyULButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                identifyULButtonItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        unitLoadPanel.add(identifyULButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(unitLoadPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

private void systemULButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_systemULButtonItemStateChanged
    systemULButtonItemStateChangedListener(evt);
}//GEN-LAST:event_systemULButtonItemStateChanged

private void identifyULButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_identifyULButtonItemStateChanged
    identifyULButtonItemStateChangedListener(evt);
}//GEN-LAST:event_identifyULButtonItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel goodsReceiptTypeComboBox;
    protected javax.swing.JRadioButton identifyULButton;
    private javax.swing.ButtonGroup identifyULButtonGroup;
    protected javax.swing.JLabel infoLabel;
    protected javax.swing.JRadioButton systemULButton;
    protected javax.swing.JPanel unitLoadLabelTextFieldPanel;
    private javax.swing.JPanel unitLoadPanel;
    protected javax.swing.JPanel unitLoadTypeComboBoxPanel;
    // End of variables declaration//GEN-END:variables

    
}
