/*
 * Copyright (c) 2012 LinogistiX GmbH
 *
 *  www.linogistix.com
 *
 *  Project myWMS-LOS
 */
package de.linogistix.inventory.browser.dialog;

import de.linogistix.common.gui.component.controls.BOAutoFilteringComboBox;
import de.linogistix.inventory.res.InventoryBundleResolver;
import de.wms2.mywms.location.StorageLocation;
import org.mywms.model.User;
import org.openide.util.NbBundle;

/**
 *
 * @author krane
 */
public class CustomerOrderStartDataPanel extends javax.swing.JPanel {

    /** Creates new form AbstractCenterPanel */
    public CustomerOrderStartDataPanel() {
        initComponents();

        fRelease.setText( NbBundle.getMessage(InventoryBundleResolver.class,"CustomerOrderStartWizard.labelRelease") );
        fComplete.setText( NbBundle.getMessage(InventoryBundleResolver.class,"CustomerOrderStartWizard.labelComplete") );
        fCombine.setText( NbBundle.getMessage(InventoryBundleResolver.class,"CustomerOrderStartWizard.labelCombine") );
        fPrio.setTitle(org.openide.util.NbBundle.getMessage(InventoryBundleResolver.class, "CustomerOrderStartWizard.labelPrio"));

        String userName = null;
        boolean userDiff = false;
        String destinationName = null;
        boolean destinationDiff = false;
        Integer prio = null;
        boolean prioDiff = false;



        fDestination.setBoClass(StorageLocation.class);
        fDestination.initAutofiltering();
        fDestination.setEditorLabelTitle( NbBundle.getMessage(InventoryBundleResolver.class,"CustomerOrderStartWizard.labelDestination") );
        if( !destinationDiff ) {
            fDestination.addItem(destinationName);
        }

        fUser.setBoClass(User.class);
        fUser.initAutofiltering();
        fUser.setEditorLabelTitle( NbBundle.getMessage(InventoryBundleResolver.class,"CustomerOrderStartWizard.labelUser") );
        if( !userDiff ) {
            fUser.addItem(userName);
        }

        if( prio != null && !prioDiff ) {
            fPrio.setText(prio.toString());
        }

    }

    public BOAutoFilteringComboBox getDestinationComboBox() {
        return fDestination;
    }

    public BOAutoFilteringComboBox getUserComboBox() {
        return fUser;
    }

    public void setPrio( String prio ) {
        fPrio.setText(prio);
    }
    public String getPrio() {
        return fPrio.getText();
    }

    public boolean isCombine() {
        return fCombine.isSelected();
    }
    public void setCombine(boolean val) {
        fCombine.setSelected(val);
    }

    public boolean isRelease() {
        return fRelease.isSelected();
    }
    public void setRelease(boolean val) {
        fRelease.setSelected(val);
    }
    
    public boolean isComplete() {
        return fComplete.isSelected();
    }
    public void setComplete(boolean val) {
        fComplete.setSelected(val);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        fRelease = new javax.swing.JCheckBox();
        fPrio = new de.linogistix.common.gui.component.controls.LOSTextField();
        fDestination = new de.linogistix.common.gui.component.controls.BOAutoFilteringComboBox();
        fUser = new de.linogistix.common.gui.component.controls.BOAutoFilteringComboBox();
        fCombine = new javax.swing.JCheckBox();
        fComplete = new javax.swing.JCheckBox();

        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setAutoscrolls(true);
        setLayout(new java.awt.GridBagLayout());

        fRelease.setSelected(true);
        fRelease.setText("Release picking order");
        fRelease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fReleaseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 0, 0, 0);
        add(fRelease, gridBagConstraints);

        fPrio.setColumns(3);
        fPrio.setTitle("Prio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        add(fPrio, gridBagConstraints);

        fDestination.setEditorLabelTitle("Destination");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(fDestination, gridBagConstraints);

        fUser.setEditorLabelTitle("User");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(fUser, gridBagConstraints);

        fCombine.setText("Combine Customer Orders");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        add(fCombine, gridBagConstraints);

        fComplete.setSelected(true);
        fComplete.setText("Only complete");
        fComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fCompleteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        add(fComplete, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void fReleaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fReleaseActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_fReleaseActionPerformed

    private void fCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fCompleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fCompleteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox fCombine;
    private javax.swing.JCheckBox fComplete;
    private de.linogistix.common.gui.component.controls.BOAutoFilteringComboBox fDestination;
    private de.linogistix.common.gui.component.controls.LOSTextField fPrio;
    private javax.swing.JCheckBox fRelease;
    private de.linogistix.common.gui.component.controls.BOAutoFilteringComboBox fUser;
    // End of variables declaration//GEN-END:variables
    
 
}
