/*
 * Copyright (c) 2006 - 2010 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.losdataimporter.storagelocation.gui_builder;

import de.linogistix.losdataimporter.res.BundleResolver;
import java.awt.event.ActionEvent;
import javax.swing.JTextField;

/**
 *
 * @author  trautm
 */
public abstract class AbstractFileChooserPanel extends javax.swing.JPanel  {

    /** Creates new form AbstractHintPanel */
    public AbstractFileChooserPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        fileChooserLabel = new javax.swing.JLabel();
        fileChooserTextField = new javax.swing.JTextField();
        fileChooserButton = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        fileChooserLabel.setText(org.openide.util.NbBundle.getMessage(BundleResolver.class, "AbstractFileChooserLabel.txt")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        add(fileChooserLabel, gridBagConstraints);

        fileChooserTextField.setPreferredSize(new java.awt.Dimension(150, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(fileChooserTextField, gridBagConstraints);

        fileChooserButton.setText("...");
        fileChooserButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        fileChooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(fileChooserButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

private void fileChooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserButtonActionPerformed
    onFileChooserButtonActionPerformed(evt);
}//GEN-LAST:event_fileChooserButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fileChooserButton;
    private javax.swing.JLabel fileChooserLabel;
    public javax.swing.JTextField fileChooserTextField;
    // End of variables declaration//GEN-END:variables

    protected abstract void onFileChooserButtonActionPerformed(ActionEvent evt);

    public JTextField getFileChooserTextField(){
        return this.fileChooserTextField;
    }
}
