/*
 * Copyright (c) 2006 - 2010 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.losdataimporter.storagelocation.gui_builder;

import de.linogistix.losdataimporter.res.BundleResolver;
import java.awt.event.ActionEvent;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author  trautm
 */
public abstract class AbstractCreateLabelsPanel extends javax.swing.JPanel  {

    /** Creates new form AbstractHintPanel */
    public AbstractCreateLabelsPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        fileChooserLabel = new javax.swing.JLabel();
        fileChooserTextField = new javax.swing.JTextField();
        fileChooserButton = new javax.swing.JButton();
        createLabelCheckBox = new javax.swing.JCheckBox();
        formatComboBox1 = new javax.swing.JComboBox();
        openCheckBox = new javax.swing.JCheckBox();
        formatLabel = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        fileChooserLabel.setText(org.openide.util.NbBundle.getMessage(BundleResolver.class, "AbstractFileChooserLabel.txt")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 30, 0, 0);
        add(fileChooserLabel, gridBagConstraints);

        fileChooserTextField.setPreferredSize(new java.awt.Dimension(150, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        add(fileChooserTextField, gridBagConstraints);

        fileChooserButton.setText("...");
        fileChooserButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        fileChooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(fileChooserButton, gridBagConstraints);

        createLabelCheckBox.setText(org.openide.util.NbBundle.getMessage(BundleResolver.class, "AbstractCreateLabelsPanel.createLabelCheckBox.text")); // NOI18N
        createLabelCheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                createLabelCheckBoxItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(createLabelCheckBox, gridBagConstraints);

        formatComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PDF | Avery/Zweckform" }));
        formatComboBox1.setPreferredSize(new java.awt.Dimension(55, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        add(formatComboBox1, gridBagConstraints);

        openCheckBox.setText(org.openide.util.NbBundle.getMessage(BundleResolver.class, "AbstractCreateLabelsPanel.openCheckBox.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 30, 0, 0);
        add(openCheckBox, gridBagConstraints);

        formatLabel.setText(org.openide.util.NbBundle.getMessage(BundleResolver.class, "AbstractCreateLabelsPanel.formatLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 30, 0, 0);
        add(formatLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

private void fileChooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserButtonActionPerformed
    onFileChooserButtonActionPerformed(evt);
}//GEN-LAST:event_fileChooserButtonActionPerformed

private void createLabelCheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_createLabelCheckBoxItemStateChanged
    if (evt.getStateChange() == java.awt.event.ItemEvent.DESELECTED){
        enableCreation(false);
    } else if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED){
        enableCreation(true);
    }
}//GEN-LAST:event_createLabelCheckBoxItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox createLabelCheckBox;
    private javax.swing.JButton fileChooserButton;
    private javax.swing.JLabel fileChooserLabel;
    public javax.swing.JTextField fileChooserTextField;
    private javax.swing.JComboBox formatComboBox1;
    private javax.swing.JLabel formatLabel;
    private javax.swing.JCheckBox openCheckBox;
    // End of variables declaration//GEN-END:variables

    protected abstract void onFileChooserButtonActionPerformed(ActionEvent evt);

    public JTextField getFileChooserTextField(){
        return this.fileChooserTextField;
    }
    
    public JComboBox getFormatComboBox(){
        return formatComboBox1;
    }
    
    public JCheckBox getCreateLabelCheckBox(){
        return createLabelCheckBox;
    }
    
    public JCheckBox getOpenCheckBox(){
        return openCheckBox;
    }

    public void enableCreation(boolean enable){
        formatLabel.setEnabled(enable);
        formatComboBox1.setEnabled(enable);
        fileChooserLabel.setEnabled(enable);
        fileChooserButton.setEnabled(enable);
        fileChooserTextField.setEnabled(enable);
        openCheckBox.setEnabled(enable);
    }
    
}
