/*
 * Copyright (c) 2006 - 2010 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.losdataimporter.storagelocation.gui_builder;

import de.linogistix.losdataimporter.res.BundleResolver;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JProgressBar;
import javax.swing.JTextArea;
import javax.swing.JTextPane;

/**
 *
 * @author  trautm
 */
public abstract class AbstractHintPanel extends javax.swing.JPanel  {

    /** Creates new form AbstractHintPanel */
    public AbstractHintPanel() {
        initComponents();
        postinit();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        hintLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane = new javax.swing.JTextPane();
        importPanel = new javax.swing.JPanel();
        importButton = new javax.swing.JButton();
        importProgressBar = new javax.swing.JProgressBar();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        hintLabel.setText(org.openide.util.NbBundle.getMessage(BundleResolver.class, "AbstractHintPanel.hintLabel.text")); // NOI18N
        jPanel1.add(hintLabel);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jTextPane.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
        jTextPane.setEditable(false);
        jScrollPane1.setViewportView(jTextPane);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        importPanel.setLayout(new java.awt.GridBagLayout());

        importButton.setText(org.openide.util.NbBundle.getMessage(BundleResolver.class, "AbstractHintPanel.importButton.text")); // NOI18N
        importButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 0);
        importPanel.add(importButton, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 0);
        importPanel.add(importProgressBar, gridBagConstraints);

        add(importPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

private void importButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importButtonActionPerformed
    onImportButtonActionPerformed(evt);
}//GEN-LAST:event_importButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hintLabel;
    private javax.swing.JButton importButton;
    private javax.swing.JPanel importPanel;
    private javax.swing.JProgressBar importProgressBar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane;
    // End of variables declaration//GEN-END:variables

   public JTextPane getTextPane(){
       return jTextPane;
   }
   
   public JProgressBar getImportProgessBar(){
       return importProgressBar;
   }
   
   public JButton getImportButton(){
       return importButton;
   }

    protected  void postinit() {
        jTextPane.setEditable(false);
        jTextPane.setContentType("text/html"); 
    }

    public abstract void onImportButtonActionPerformed(ActionEvent evt) ;

}
