/*
 * Copyright (c) 2006 - 2010 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.common.gui.component.gui_builder;

import de.linogistix.common.res.CommonBundleResolver;
import de.linogistix.common.gui.listener.MinimumSizeComponentListener;

import java.awt.Dialog;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import org.openide.DialogDescriptor;
import org.openide.DialogDisplayer;
import org.openide.explorer.propertysheet.PropertySheet;
import org.openide.util.HelpCtx;
import org.openide.util.NbBundle;

/**
 *
 * @author  artur
 */
public class AbstractBOChooser extends javax.swing.JPanel implements ActionListener {

    public DialogDescriptor dialogDescriptor;
    protected Dialog dialog;
    public final static String OK_BUTTON = "Ok";
    public final static String CANCEL_BUTTON = "Cancel";
    protected PropertySheet detailView;
// Create options
    JButton options[] = new JButton[]{
        new CustomButton(NbBundle.getMessage(CommonBundleResolver.class, OK_BUTTON), NbBundle.getMessage(CommonBundleResolver.class, OK_BUTTON), OK_BUTTON),
        new CustomButton(NbBundle.getMessage(CommonBundleResolver.class, CANCEL_BUTTON), NbBundle.getMessage(CommonBundleResolver.class, CANCEL_BUTTON), CANCEL_BUTTON)
    };

    /** Creates new form detailDialog */
    public AbstractBOChooser() {
        initComponents();
        postInit();
        dialogDescriptor = new DialogDescriptor(
                this,
                NbBundle.getMessage(CommonBundleResolver.class, "Empty"),
                true,
                options,
                options[1], //welcher defaultmaessig selektiert sein soll
                DialogDescriptor.DEFAULT_ALIGN,
                null, //getHelpCtx(),
                this);
//        dialogDescriptor.setClosingOptions(close);  
        dialogDescriptor.setClosingOptions(new Object[]{options[1]});
    }

    public HelpCtx getHelpCtx() {
        return new HelpCtx("de.linogistix.ltu.processes.storage.res.help.help.html");
    }

    public void actionPerformed(final java.awt.event.ActionEvent ev) {
    }

    public void showDialog() {
        dialog = DialogDisplayer.getDefault().createDialog(dialogDescriptor);

        dialog.setModal(true);

        new MinimumSizeComponentListener(dialog, 800, 500);

        dialog.setVisible(true);
        
    }

    public void closeDialog() {
        dialog.dispose();
    }

    private void postInit() {
    }

    public JButton getOKButton() {
        return options[0];
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public class CustomButton extends JButton {

        public CustomButton(String title, String mnemonic, String actionCommand) {
            super(title);
            if( mnemonic != null && mnemonic.length() > 0) {
                setMnemonic(mnemonic.charAt(0));
            }
            setActionCommand(actionCommand);
        }
    }
}
