/*
 * Copyright (c) 2006 - 2010 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.common.gui.component.gui_builder;

import de.linogistix.common.gui.component.view.LOSListView;
import de.linogistix.common.gui.component.controls.LosLabel;
import de.linogistix.common.res.CommonBundleResolver;

/**
 *
 * @author  Jordan
 */
public class AbstractListChooserView extends javax.swing.JPanel {

    private LOSListView chosenListView;
    
    /** Creates new form AbstractListChooserView */
    public AbstractListChooserView() {
        initComponents();
        
        chooseStockButton.setIcon(
                new javax.swing.ImageIcon(CommonBundleResolver.class.getResource("/de/linogistix/common/res/icon/Add.png"))); // NOI18N
        
        removeChosenStockButton.setIcon(
                new javax.swing.ImageIcon(CommonBundleResolver.class.getResource("/de/linogistix/common/res/icon/Remove.png"))); // NOI18N
        
        chosenListView = new LOSListView();
        
        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridheight = 1;
        gbc.fill = java.awt.GridBagConstraints.VERTICAL;
        gbc.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gbc.weighty = 1;
        
        chosenListViewPanel.add(chosenListView, gbc);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        chosenListViewPanel = new javax.swing.JPanel();
        chooseButtonPanel = new javax.swing.JPanel();
        chooseStockButton = new javax.swing.JButton();
        removeChosenStockButton = new javax.swing.JButton();
        queryListLabel = new LosLabel();
        queryPanel = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());

        chosenListViewPanel.setMinimumSize(new java.awt.Dimension(150, 300));
        chosenListViewPanel.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 0.5;
        add(chosenListViewPanel, gridBagConstraints);

        chooseButtonPanel.setMaximumSize(new java.awt.Dimension(39, 32767));
        chooseButtonPanel.setMinimumSize(new java.awt.Dimension(39, 112));
        chooseButtonPanel.setPreferredSize(new java.awt.Dimension(39, 112));
        chooseButtonPanel.setLayout(new java.awt.GridBagLayout());

        chooseStockButton.setToolTipText("down");
        chooseStockButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        chooseButtonPanel.add(chooseStockButton, gridBagConstraints);

        removeChosenStockButton.setToolTipText("up");
        removeChosenStockButton.setMargin(new java.awt.Insets(2, 2, 2, 2));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        chooseButtonPanel.add(removeChosenStockButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        add(chooseButtonPanel, gridBagConstraints);

        queryListLabel.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        add(queryListLabel, gridBagConstraints);
        queryListLabel.getAccessibleContext().setAccessibleName("");

        queryPanel.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(queryPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chooseButtonPanel;
    protected javax.swing.JButton chooseStockButton;
    private javax.swing.JPanel chosenListViewPanel;
    protected javax.swing.JLabel queryListLabel;
    protected javax.swing.JPanel queryPanel;
    protected javax.swing.JButton removeChosenStockButton;
    // End of variables declaration//GEN-END:variables

    public LOSListView getChosenListView(){
        return chosenListView;
    }
}
