/*
 * Copyright (c) 2006 - 2010 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.common.userlogin;

import de.linogistix.common.res.CommonBundleResolver;

public class LoginPanel extends javax.swing.JPanel {

    public LoginPanel() {
        initComponents();
        postInit();
        
        userLabel.setText(org.openide.util.NbBundle.getMessage(CommonBundleResolver.class, "LoginPanel.userLabel.text")); // NOI18N
        passwordLabel.setText(org.openide.util.NbBundle.getMessage(CommonBundleResolver.class, "LoginPanel.passwordLabel.text")); // NOI18N
    }

    public String getUsername() {
        return nameTextField.getText();
    }

    public String getPassword() {
        return new String(passwordTextField.getPassword());
    }

    public void setUsername(String text) {
        nameTextField.setText(text);
    }

    public void setInfo(String msg) {
        infoLabel.setText(msg);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        centerPanel = new javax.swing.JPanel();
        userLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JPasswordField();
        eastPanel = new javax.swing.JPanel();
        iconLabel = new javax.swing.JLabel();
        southPanel = new javax.swing.JPanel();
        infoLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(350, 100));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        centerPanel.setPreferredSize(new java.awt.Dimension(250, 100));
        centerPanel.setLayout(new java.awt.GridBagLayout());

        userLabel.setText(org.openide.util.NbBundle.getMessage(CommonBundleResolver.class, "LoginPanel.userLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 10, 0, 5);
        centerPanel.add(userLabel, gridBagConstraints);

        passwordLabel.setText(org.openide.util.NbBundle.getMessage(CommonBundleResolver.class, "LoginPanel.passwordLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 18, 5);
        centerPanel.add(passwordLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 10);
        centerPanel.add(nameTextField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 18, 10);
        centerPanel.add(passwordTextField, gridBagConstraints);

        add(centerPanel, java.awt.BorderLayout.CENTER);

        eastPanel.setLayout(new java.awt.BorderLayout());

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/linogistix/common/res/icon/login.png"))); // NOI18N
        eastPanel.add(iconLabel, java.awt.BorderLayout.CENTER);

        add(eastPanel, java.awt.BorderLayout.EAST);

        southPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        infoLabel.setForeground(new java.awt.Color(255, 0, 0));
        infoLabel.setText("  "); // NOI18N
        southPanel.add(infoLabel);

        add(southPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
    formComponentShownListener(evt);
}//GEN-LAST:event_formComponentShown

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel eastPanel;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel infoLabel;
    public javax.swing.JTextField nameTextField;
    private javax.swing.JLabel passwordLabel;
    public javax.swing.JPasswordField passwordTextField;
    private javax.swing.JPanel southPanel;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
    public void postInit() {

    }
    
    public void setIcon(String pic) {
        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(pic)));        
    }
    
    protected void formComponentShownListener(java.awt.event.ComponentEvent evt) {
        
    }
}
