/*
 * Copyright (c) 2006 - 2010 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.common.bobrowser.bo.editor;

import de.linogistix.common.bobrowser.bo.*;
import de.linogistix.common.res.icon.IconResolver;
import java.beans.BeanInfo;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author  trautm
 */
public class BOEditorHeader extends javax.swing.JPanel {

    protected Icon documentIcon = new javax.swing.ImageIcon(
            IconResolver.class.getResource(
            "/de/linogistix/common/res/icon/Document32.png"));

    /** Creates new form BOEditorHeader */
    public BOEditorHeader(BOEntityNode node) {
        this(node, null);
    }

    /** Creates new form BOEditorHeader */
    public BOEditorHeader(BOEntityNode node, String additionalInfo) {
        this(new ImageIcon(node.getIcon(BeanInfo.ICON_COLOR_32x32)), node.getDisplayName(), additionalInfo);
    }

    public BOEditorHeader(Icon icon, String descr, String additionalInfo) {
        initComponents();
        
        if (icon != null) {
            iconLabel.setIcon(icon);
        }
        StringBuffer b = new StringBuffer(descr);
        if (additionalInfo != null && (!additionalInfo.equals(""))) {
            b.append(" - " + additionalInfo);
        }
        iconLabel.setText(new String(b));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconLabel = new javax.swing.JLabel();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        iconLabel.setIcon(documentIcon);
        iconLabel.setText(":Typ:Identity");
        add(iconLabel);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconLabel;
    // End of variables declaration//GEN-END:variables
}
