/*
 * Copyright (c) 2006 - 2010 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.wmsprocesses.processes.order.gui.component;


import java.awt.BorderLayout;
import javax.swing.BorderFactory;
import javax.swing.JPanel;
import org.openide.windows.TopComponent;

/**
 *
 * @author  artur
 */
public class TopComponentPanel extends JPanel {
    
    HeaderPanel headerPanel = new HeaderPanel(this);
    FooterPanel footerPanel = new FooterPanel(this);
    CenterPanel centerPanel = new CenterPanel(this);
    TopComponent topComponent;
    
    /** Creates new form TopComponentPanel */
    public TopComponentPanel(TopComponent topComponent) {
        initComponents();
        postInit();
        this.topComponent = topComponent;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
 
    private void postInit() {
        setBorder(BorderFactory.createEmptyBorder(0,10,0,10));
        add(headerPanel, BorderLayout.NORTH);
        add(centerPanel, BorderLayout.CENTER);
        add(footerPanel, BorderLayout.SOUTH);
    }
}
