/*
 * Copyright (c) 2012 LinogistiX GmbH
 *
 *  www.linogistix.com
 *
 *  Project myWMS-LOS
 */
package de.linogistix.wmsprocesses.carriertransfer;

import de.linogistix.common.gui.component.controls.BOAutoFilteringComboBox;
import de.linogistix.los.location.model.LOSUnitLoad;
import de.linogistix.wmsprocesses.res.WMSProcessesBundleResolver;
import org.openide.util.NbBundle;

/**
 *
 * @author krane
 */
public class CarrierTransferDataPanel extends javax.swing.JPanel {

    /** Creates new form AbstractCenterPanel */
    public CarrierTransferDataPanel() {
        
        initComponents();

        unitLoadAutoFilteringComboBox.setBoClass(LOSUnitLoad.class);
        unitLoadAutoFilteringComboBox.initAutofiltering();
        unitLoadAutoFilteringComboBox.setEditorLabelTitle(NbBundle.getMessage(WMSProcessesBundleResolver.class, "Carrier.Source"));
        unitLoadAutoFilteringComboBox.setEditorLabelText();
        unitLoadAutoFilteringComboBox.setEnabled(true);


        destinationAutofilteringComboBox.setBoClass(LOSUnitLoad.class);
        destinationAutofilteringComboBox.initAutofiltering();
        destinationAutofilteringComboBox.setEditorLabelTitle(NbBundle.getMessage(WMSProcessesBundleResolver.class, "Carrier.Destination"));
        destinationAutofilteringComboBox.setEditorLabelText();
        destinationAutofilteringComboBox.setEnabled(true);


        sourceLocLabel.setText(NbBundle.getMessage(WMSProcessesBundleResolver.class, "location")+":");
        sourceLocText.setText("");
        destinationLocLabel.setText(NbBundle.getMessage(WMSProcessesBundleResolver.class, "location")+":");
        destinationLocText.setText("");
    }
       
    public BOAutoFilteringComboBox getUnitLoadAutoFilteringComboBox() {
        return unitLoadAutoFilteringComboBox;
    }
    public BOAutoFilteringComboBox getDestinationAutofilteringComboBox() {
        return destinationAutofilteringComboBox;
    }

    public void setSourceInfoText(String text) {
        sourceLocText.setText(text);
    }
    public void setDestinationInfoText(String text) {
        destinationLocText.setText(text);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        unitLoadAutoFilteringComboBox = new de.linogistix.common.gui.component.controls.BOAutoFilteringComboBox();
        sourceInfoPanel = new javax.swing.JPanel();
        sourceLocLabel = new javax.swing.JLabel();
        sourceLocText = new javax.swing.JLabel();
        destinationAutofilteringComboBox = new de.linogistix.common.gui.component.controls.BOAutoFilteringComboBox();
        destinationInfoPanel = new javax.swing.JPanel();
        destinationLocLabel = new javax.swing.JLabel();
        destinationLocText = new javax.swing.JLabel();

        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setAutoscrolls(true);
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jPanel1.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(unitLoadAutoFilteringComboBox, gridBagConstraints);

        sourceInfoPanel.setLayout(new java.awt.GridBagLayout());

        sourceLocLabel.setForeground(new java.awt.Color(70, 70, 70));
        sourceLocLabel.setText("sourceLabel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        sourceInfoPanel.add(sourceLocLabel, gridBagConstraints);

        sourceLocText.setForeground(new java.awt.Color(70, 70, 70));
        sourceLocText.setText("location");
        sourceLocText.setMinimumSize(new java.awt.Dimension(250, 15));
        sourceLocText.setPreferredSize(new java.awt.Dimension(200, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        sourceInfoPanel.add(sourceLocText, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel1.add(sourceInfoPanel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel1.add(destinationAutofilteringComboBox, gridBagConstraints);

        destinationInfoPanel.setLayout(new java.awt.GridBagLayout());

        destinationLocLabel.setForeground(new java.awt.Color(70, 70, 70));
        destinationLocLabel.setText("sourceLabel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        destinationInfoPanel.add(destinationLocLabel, gridBagConstraints);

        destinationLocText.setForeground(new java.awt.Color(70, 70, 70));
        destinationLocText.setText("location");
        destinationLocText.setMinimumSize(new java.awt.Dimension(250, 15));
        destinationLocText.setPreferredSize(new java.awt.Dimension(200, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        destinationInfoPanel.add(destinationLocText, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel1.add(destinationInfoPanel, gridBagConstraints);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected de.linogistix.common.gui.component.controls.BOAutoFilteringComboBox destinationAutofilteringComboBox;
    private javax.swing.JPanel destinationInfoPanel;
    private javax.swing.JLabel destinationLocLabel;
    private javax.swing.JLabel destinationLocText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel sourceInfoPanel;
    private javax.swing.JLabel sourceLocLabel;
    private javax.swing.JLabel sourceLocText;
    protected de.linogistix.common.gui.component.controls.BOAutoFilteringComboBox unitLoadAutoFilteringComboBox;
    // End of variables declaration//GEN-END:variables
    
 
}
