/*
 * Copyright (c) 2006 - 2010 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.reports.gui.component;

import de.linogistix.common.gui.component.windows.JSaveDialog;
import de.linogistix.common.util.ExceptionAnnotator;
import de.linogistix.reports.res.ReportsBundleResolver;
import java.io.File;
import java.io.IOException;
import javax.swing.JTextField;

/**
 *
 * @author  trautm
 */
public class BOExportWizardFileJPanel extends javax.swing.JPanel {

    File file;
    String fileEnding;
    String description;
    String defaultFileName;

    /** Creates new form BOExportWizardSelectionJPanel */
    public BOExportWizardFileJPanel(String fileEnding, String description, String defaultFileName) {
        this.fileEnding = fileEnding;
        this.description = description;
        this.defaultFileName = defaultFileName;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        questionLabel = new javax.swing.JLabel();
        fileNameTextfield = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        openCheckBox = new java.awt.Checkbox();

        setLayout(new java.awt.GridBagLayout());

        questionLabel.setText(org.openide.util.NbBundle.getMessage(ReportsBundleResolver.class, "BOExportWizard.saveasLabel")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        add(questionLabel, gridBagConstraints);

        fileNameTextfield.setMinimumSize(new java.awt.Dimension(100, 22));
        fileNameTextfield.setPreferredSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(fileNameTextfield, gridBagConstraints);

        jButton1.setText("...");
        jButton1.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(jButton1, gridBagConstraints);

        openCheckBox.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        openCheckBox.setLabel(org.openide.util.NbBundle.getMessage(ReportsBundleResolver.class, "BOExportWizard.open")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        add(openCheckBox, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    JSaveDialog saveDialog = null;
    if( fileEnding == null ) {
        saveDialog = new JSaveDialog(".xls", "*.xls", "export.xls");
    }
    else {
        saveDialog = new JSaveDialog(fileEnding, description, defaultFileName);
    }

    int returnValue = saveDialog.showSaveDialog(null);
    if ((returnValue == javax.swing.JFileChooser.APPROVE_OPTION)) {
        this.file = saveDialog.getSelectedFile();
            try {
                fileNameTextfield.setText(file.getCanonicalPath());
            } catch (IOException ex) {
                ExceptionAnnotator.annotate(ex);
            }
    }
    
}//GEN-LAST:event_jButton1ActionPerformed

public JTextField getFileNameTextField(){
    return this.fileNameTextfield;
}
public String getSelectedFileName(){
    return fileNameTextfield.getText();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    javax.swing.JTextField fileNameTextfield;
    private javax.swing.JButton jButton1;
    java.awt.Checkbox openCheckBox;
    private javax.swing.JLabel questionLabel;
    // End of variables declaration//GEN-END:variables

}
