/*
 * Copyright (c) 2006 - 2010 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */

package de.linogistix.los.inventory.ws.jaxwsgen;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;



/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-hudson-48-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "QueryInventoryBeanService", targetNamespace = "http://ws.inventory.los.linogistix.de/", wsdlLocation = "file:/D:/develop/trautm/linogistix.cms/server.app/los.inventory-ejb/test/de/linogistix/los/inventory/ws/jaxwsgen/queryinventory.wsdl")
public class QueryInventoryBeanService
    extends Service
{

    private final static URL QUERYINVENTORYBEANSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(de.linogistix.los.inventory.ws.jaxwsgen.QueryInventoryBeanService.class.getName());

    static {
        URL url = null;
        try {
        	String urlStr = "de/linogistix/los/inventory/ws/jaxwsgen/queryinventory.wsdl";
            url = QueryInventoryBeanService.class.getResource(urlStr);
            if (url == null){
            	urlStr =  "/" + urlStr;
            	url = QueryInventoryBeanService.class.getResource(urlStr);
            	if (url == null){
            		throw new MalformedURLException();
            	}
            }
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        QUERYINVENTORYBEANSERVICE_WSDL_LOCATION = url;
    }

    public QueryInventoryBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QueryInventoryBeanService() {
        super(QUERYINVENTORYBEANSERVICE_WSDL_LOCATION, new QName("http://ws.inventory.los.linogistix.de/", "QueryInventoryBeanService"));
    }

    /**
     * 
     * @return
     *     returns QueryInventory
     */
    @WebEndpoint(name = "QueryInventoryBeanPort")
    public QueryInventory getQueryInventoryBeanPort() {
        return super.getPort(new QName("http://ws.inventory.los.linogistix.de/", "QueryInventoryBeanPort"), QueryInventory.class);
    }

}
