/*
 * Copyright (c) 2006 - 2010 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */

package de.linogistix.los.inventory.ws.jaxwsgen;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-hudson-48-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "QueryInventory", targetNamespace = "http://ws.inventory.los.linogistix.de/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface QueryInventory {


    /**
     * 
     * @param clientRef
     * @param articleRef
     * @param consolidateLot
     * @return
     *     returns de.linogistix.los.inventory.ws.jaxwsgen.InventoryTOArray
     * @throws InventoryException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public InventoryTOArray getInventoryByArticle(
        @WebParam(name = "clientRef", partName = "clientRef")
        String clientRef,
        @WebParam(name = "articleRef", partName = "articleRef")
        String articleRef,
        @WebParam(name = "consolidateLot", partName = "consolidateLot")
        boolean consolidateLot)
        throws InventoryException_Exception
    ;

    /**
     * 
     * @param clientRef
     * @param articleRef
     * @param lotRef
     * @return
     *     returns de.linogistix.los.inventory.ws.jaxwsgen.InventoryTO
     * @throws InventoryException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public InventoryTO getInventoryByLot(
        @WebParam(name = "clientRef", partName = "clientRef")
        String clientRef,
        @WebParam(name = "articleRef", partName = "articleRef")
        String articleRef,
        @WebParam(name = "lotRef", partName = "lotRef")
        String lotRef)
        throws InventoryException_Exception
    ;

    /**
     * 
     * @param clientRef
     * @param consolidateLot
     * @return
     *     returns de.linogistix.los.inventory.ws.jaxwsgen.InventoryTOArray
     * @throws InventoryException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    public InventoryTOArray getInventoryList(
        @WebParam(name = "clientRef", partName = "clientRef")
        String clientRef,
        @WebParam(name = "consolidateLot", partName = "consolidateLot")
        boolean consolidateLot)
        throws InventoryException_Exception
    ;

}
