/*
 * Copyright (c) 2006 - 2010 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.common.bobrowser.crud.gui.gui_builder;

import de.linogistix.common.bobrowser.bo.BO;
import de.linogistix.common.res.CommonBundleResolver;

/**
 *
 * @author  trautm
 */
public abstract class AbstractBOLockPanel extends javax.swing.JPanel {
    protected BO bo;

    /** Creates new form AbstractBOLockPanel */
    public AbstractBOLockPanel(BO bo){
        this.bo = bo;
        initComponents();
        initLockComboBox();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lockIntPanel = new javax.swing.JPanel();
        lockLabel = new javax.swing.JLabel();
        lockComboBox = new javax.swing.JComboBox();
        lockCausePanel = new javax.swing.JPanel();
        causeLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        causeTextArea = new javax.swing.JTextPane();

        setPreferredSize(new java.awt.Dimension(300, 275));
        setLayout(new java.awt.BorderLayout());

        lockIntPanel.setLayout(new java.awt.GridBagLayout());

        lockLabel.setText(org.openide.util.NbBundle.getMessage(CommonBundleResolver.class, "lock")); // NOI18N
        lockLabel.setMaximumSize(new java.awt.Dimension(250, 22));
        lockLabel.setPreferredSize(new java.awt.Dimension(250, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        lockIntPanel.add(lockLabel, gridBagConstraints);

        lockComboBox.setPreferredSize(new java.awt.Dimension(250, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        lockIntPanel.add(lockComboBox, gridBagConstraints);

        add(lockIntPanel, java.awt.BorderLayout.NORTH);

        lockCausePanel.setLayout(new java.awt.BorderLayout());

        causeLabel.setText(org.openide.util.NbBundle.getMessage(CommonBundleResolver.class, "lockCause")); // NOI18N
        causeLabel.setMaximumSize(new java.awt.Dimension(250, 22));
        causeLabel.setPreferredSize(new java.awt.Dimension(250, 22));
        lockCausePanel.add(causeLabel, java.awt.BorderLayout.NORTH);

        causeTextArea.setMinimumSize(new java.awt.Dimension(200, 100));
        jScrollPane1.setViewportView(causeTextArea);

        lockCausePanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(lockCausePanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel causeLabel;
    protected javax.swing.JTextPane causeTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel lockCausePanel;
    protected javax.swing.JComboBox lockComboBox;
    private javax.swing.JPanel lockIntPanel;
    private javax.swing.JLabel lockLabel;
    // End of variables declaration//GEN-END:variables

    public abstract void initLockComboBox();
    
    
    
}
