/*
 * Copyright (c) 2006 - 2010 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.stocktaking.process.gui;


import org.openide.explorer.ExplorerManager;
import org.openide.explorer.view.TreeTableView;

/**
 *
 * @author  trautm
 */
public abstract class StockTakingRecordAbstractPanel 
        extends javax.swing.JPanel 
        implements ExplorerManager.Provider
{
    protected TreeTableView beanView;
    
    /** Creates new form AbstractCenterPanel */
    public StockTakingRecordAbstractPanel() {
        initComponents(); 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stockRecordViewPanel = new javax.swing.JPanel();

        setAlignmentX(1.0F);
        setAlignmentY(1.0F);
        setLayout(new java.awt.BorderLayout());

        stockRecordViewPanel.setLayout(new java.awt.BorderLayout());
        add(stockRecordViewPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JPanel stockRecordViewPanel;
    // End of variables declaration//GEN-END:variables
     
    
}
