/*
 * Copyright (c) 2006 - 2012 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.wmsprocesses.unitloadtransfer;

import de.linogistix.common.gui.component.controls.BOAutoFilteringComboBox;
import de.linogistix.common.gui.component.controls.LosLabel;
import de.linogistix.los.location.model.LOSStorageLocation;
import de.linogistix.los.location.model.LOSUnitLoad;
import de.linogistix.wmsprocesses.res.WMSProcessesBundleResolver;
import javax.swing.JCheckBox;
import org.openide.util.NbBundle;

/**
 *
 * @author  trautm
 */
public class UnitLoadTransferDataPanel extends javax.swing.JPanel {

    /** Creates new form AbstractCenterPanel */
    public UnitLoadTransferDataPanel() {
        
        initComponents();

        unitLoadAutoFilteringComboBox.setBoClass(LOSUnitLoad.class);
        unitLoadAutoFilteringComboBox.initAutofiltering();
        unitLoadAutoFilteringComboBox.setEditorLabelTitle(NbBundle.getMessage(de.linogistix.common.res.CommonBundleResolver.class, "unitLoad"));
        unitLoadAutoFilteringComboBox.setEditorLabelText();
        unitLoadAutoFilteringComboBox.setEnabled(true);


        destinationAutofilteringComboBox.setBoClass(LOSStorageLocation.class);
        destinationAutofilteringComboBox.initAutofiltering();
        destinationAutofilteringComboBox.setEditorLabelTitle(NbBundle.getMessage(WMSProcessesBundleResolver.class, "AbstractChooseDestinationPanel.destinationSl"));
        destinationAutofilteringComboBox.setEditorLabelText();
        destinationAutofilteringComboBox.setEnabled(true);

        slReserveCheckBox.setEnabled(false);
        getSlReserveLabel().setEnabled(false);
        getSlReserveLabel().setText();
        getSlReserveLabel().setTitleText(
                NbBundle.getMessage(WMSProcessesBundleResolver.class, "AbstractChooseDestinationPanel.removeReservationFromSl"));
        getSlReserveLabel().setText(NbBundle.getMessage(WMSProcessesBundleResolver.class, "AbstractChooseDestinationPanel.removeReservationFromSl"));

        slLockCheckBox.setEnabled(false);
        getSlLockLabel().setEnabled(false);
        getSlLockLabel().setText();
        getSlLockLabel().setTitleText(
                NbBundle.getMessage(WMSProcessesBundleResolver.class, "AbstractChooseDestinationPanel.removeSlLock"));
        getSlLockLabel().setText(NbBundle.getMessage(WMSProcessesBundleResolver.class, "AbstractChooseDestinationPanel.removeSlLock"));

        sourceLocLabel.setText(NbBundle.getMessage(WMSProcessesBundleResolver.class, "AbstractChooseDestinationPanel.sourceLocation")+":");
        sourceLocText.setText("");
    }
       
    public LosLabel getSlReserveLabel(){
        return (LosLabel) slReserveLabel;
    }
    
    public LosLabel getSlLockLabel(){
        return (LosLabel) slLockLabel;
    }

    public JCheckBox getSlReserveCheckbox() {
        return slReserveCheckBox;
    }
    public JCheckBox getSlLockCheckbox() {
        return slLockCheckBox;
    }
    public BOAutoFilteringComboBox getUnitLoadAutoFilteringComboBox() {
        return unitLoadAutoFilteringComboBox;
    }
    public BOAutoFilteringComboBox getDestinationAutofilteringComboBox() {
        return destinationAutofilteringComboBox;
    }

    public void setSourceInfoText(String text) {
        sourceLocText.setText(text);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        unitLoadAutoFilteringComboBox = new de.linogistix.common.gui.component.controls.BOAutoFilteringComboBox();
        sourceInfoPanel = new javax.swing.JPanel();
        sourceLocLabel = new javax.swing.JLabel();
        sourceLocText = new javax.swing.JLabel();
        destinationAutofilteringComboBox = new de.linogistix.common.gui.component.controls.BOAutoFilteringComboBox();
        slLockCheckBox = new javax.swing.JCheckBox();
        slLockLabel = new LosLabel();
        slReserveCheckBox = new javax.swing.JCheckBox();
        slReserveLabel = new LosLabel();

        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setAutoscrolls(true);
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jPanel1.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(unitLoadAutoFilteringComboBox, gridBagConstraints);

        sourceInfoPanel.setLayout(new java.awt.GridBagLayout());

        sourceLocLabel.setForeground(new java.awt.Color(70, 70, 70));
        sourceLocLabel.setText("sourceLabel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        sourceInfoPanel.add(sourceLocLabel, gridBagConstraints);

        sourceLocText.setForeground(new java.awt.Color(70, 70, 70));
        sourceLocText.setText("location");
        sourceLocText.setMinimumSize(new java.awt.Dimension(250, 15));
        sourceLocText.setPreferredSize(new java.awt.Dimension(200, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        sourceInfoPanel.add(sourceLocText, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel1.add(sourceInfoPanel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel1.add(destinationAutofilteringComboBox, gridBagConstraints);

        slLockCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slLockCheckBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 0);
        jPanel1.add(slLockCheckBox, gridBagConstraints);

        slLockLabel.setText(org.openide.util.NbBundle.getMessage(WMSProcessesBundleResolver.class, "UnitLoadTransferDataPanel.slLockLabel.text")); // NOI18N
        slLockLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 5, 0, 0);
        jPanel1.add(slLockLabel, gridBagConstraints);

        slReserveCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slReserveCheckBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 0);
        jPanel1.add(slReserveCheckBox, gridBagConstraints);

        slReserveLabel.setText(org.openide.util.NbBundle.getMessage(WMSProcessesBundleResolver.class, "UnitLoadTransferDataPanel.slReserveLabel.text")); // NOI18N
        slReserveLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 10, 0);
        jPanel1.add(slReserveLabel, gridBagConstraints);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

private void slReserveCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slReserveCheckBoxActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_slReserveCheckBoxActionPerformed

private void slLockCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slLockCheckBoxActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_slLockCheckBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected de.linogistix.common.gui.component.controls.BOAutoFilteringComboBox destinationAutofilteringComboBox;
    private javax.swing.JPanel jPanel1;
    protected javax.swing.JCheckBox slLockCheckBox;
    protected javax.swing.JLabel slLockLabel;
    protected javax.swing.JCheckBox slReserveCheckBox;
    protected javax.swing.JLabel slReserveLabel;
    private javax.swing.JPanel sourceInfoPanel;
    private javax.swing.JLabel sourceLocLabel;
    private javax.swing.JLabel sourceLocText;
    protected de.linogistix.common.gui.component.controls.BOAutoFilteringComboBox unitLoadAutoFilteringComboBox;
    // End of variables declaration//GEN-END:variables

   
 
}
