/*
 * Copyright (c) 2006 - 2012 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.wmsprocesses.stockunittransfer;

import de.linogistix.wmsprocesses.res.WMSProcessesBundleResolver;

/**
 *
 * @author  trautm
 */
public class StockUnitTransferInfoPanel extends javax.swing.JPanel {

    /** Creates new form AbstractCreateWizardInfoPanel */
    public StockUnitTransferInfoPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        additionalInfoPanel = new javax.swing.JLabel();
        additionalInfolScrollPane = new javax.swing.JScrollPane();
        additionalInfoTextArea = new javax.swing.JTextArea();

        setLayout(new java.awt.GridBagLayout());

        additionalInfoPanel.setText(org.openide.util.NbBundle.getMessage(WMSProcessesBundleResolver.class, "AbstractCenterPanel.additionalInfoLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(additionalInfoPanel, gridBagConstraints);

        additionalInfolScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        additionalInfolScrollPane.setMinimumSize(new java.awt.Dimension(150, 50));
        additionalInfolScrollPane.setPreferredSize(new java.awt.Dimension(300, 92));

        additionalInfoTextArea.setColumns(20);
        additionalInfoTextArea.setLineWrap(true);
        additionalInfoTextArea.setRows(5);
        additionalInfolScrollPane.setViewportView(additionalInfoTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 99.99;
        gridBagConstraints.weighty = 0.5;
        add(additionalInfolScrollPane, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel additionalInfoPanel;
    protected javax.swing.JTextArea additionalInfoTextArea;
    private javax.swing.JScrollPane additionalInfolScrollPane;
    // End of variables declaration//GEN-END:variables

    public String getInfo() {
        return additionalInfoTextArea.getText();
    }
    public void setInfo(String info) {
        additionalInfoTextArea.setText(info);
    }

}
