/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BOCommentDetailViewPanel.java
 *
 * Created on 23.09.2011, 22:22:57
 */

package de.linogistix.common.bobrowser.bo.detailview;

import de.linogistix.common.bobrowser.bo.BOEntityNode;
import de.linogistix.common.bobrowser.crud.gui.component.BOAdditionalContentWizard;
import de.linogistix.common.res.CommonBundleResolver;
import de.linogistix.common.util.CursorControl;
import de.linogistix.common.util.ExceptionAnnotator;
import de.linogistix.los.crud.BusinessObjectCRUDRemote;
import java.awt.Dialog;
import javax.swing.JTextArea;
import org.openide.nodes.Node;
import org.openide.util.NbBundle;
import org.mywms.model.BasicEntity;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;

/**
 *
 * @author andreas
 */
public class BOCommentDetailEditPanel extends AbstractDetailViewPanel {

    /** Creates new form BOCommentDetailViewPanel */
    public BOCommentDetailEditPanel() {
        initComponents();
    }

    public JTextArea getCommentArea(){
        return commentArea;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        commentArea = new javax.swing.JTextArea();
        filler1 = new javax.swing.JLabel();
        filler2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        filler3 = new javax.swing.JLabel();
        iconLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        commentArea.setColumns(20);
        commentArea.setLineWrap(true);
        commentArea.setRows(5);
        commentArea.setWrapStyleWord(true);
        commentArea.setDisabledTextColor(java.awt.Color.black);
        commentArea.setMargin(new java.awt.Insets(10, 5, 20, 10));
        jScrollPane1.setViewportView(commentArea);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        filler1.setText("  ");
        add(filler1, java.awt.BorderLayout.NORTH);

        filler2.setText("  ");
        add(filler2, java.awt.BorderLayout.LINE_END);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        filler3.setText("  ");
        jPanel1.add(filler3);

        add(jPanel1, java.awt.BorderLayout.SOUTH);

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/linogistix/common/res/icon/Info32.png"))); // NOI18N
        iconLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(iconLabel, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea commentArea;
    private javax.swing.JLabel filler1;
    private javax.swing.JLabel filler2;
    private javax.swing.JLabel filler3;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setNode(Node node) {
        if (node == null){
            commentArea.setText("");
        }
        else{
            BOEntityNode entityNode = (BOEntityNode) node;
            commentArea.setText(entityNode.getBo().getAdditionalContent());
        }
    }

    @Override
    public String getPanelName() {
        return NbBundle.getMessage(CommonBundleResolver.class, "BOCommentDetailViewPanel.panelName");
    }

    public String getComment() {
        return commentArea.getText();
    }

    public void setComment(String comment) {
        this.commentArea.setText(comment);
    }

  
}
